package com.abc.recorderdemo.db.wb;

import com.abcpen.livemeeting.sdk.wbrecord.mo.WeikeMo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weikeMoDaoConfig;

    private final WeikeMoDao weikeMoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weikeMoDaoConfig = daoConfigMap.get(WeikeMoDao.class).clone();
        weikeMoDaoConfig.initIdentityScope(type);

        weikeMoDao = new WeikeMoDao(weikeMoDaoConfig, this);

        registerDao(WeikeMo.class, weikeMoDao);
    }
    
    public void clear() {
        weikeMoDaoConfig.clearIdentityScope();
    }

    public WeikeMoDao getWeikeMoDao() {
        return weikeMoDao;
    }

}
